spring:
  couchbase:
    connection-string: "127.0.0.1"
    user-name: "mdep"
    password: "Create123@"
    bucket-name: "product"

  zipkin:
    base-url: http://localhost:9411/
  
logging:
  file: 
    name: /Users/harshith.sr/Downloads/logs/elk-stack.log